spring:
 mail:
    host: email-smtp.us-west-1.amazonaws.com
    username: AKIA4EN6LWAKZNL37VUA
    password: BMh4lKN23tY0QtNmYFnnf8lCA40KrZJ4JmNnPbWOIO2E
    sender: notificaciones@boyertech.com.mx
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
          port: '587'
        transport:
          protocol: smtp  
