spring:
  cloud:
   gateway: 
      routes: 
        - id: my_route
          uri: http://httpbin.org:80
          predicates: 
            - Path=/get/**
          filters:
            - AddRequestHeader=Hello,World
           # - StripPrefix=1  
# ws-authenticator
# user endpoint
        - id: ws-authenticator
          uri: lb://ws-authenticator
          predicates: 
            - Path=/ws-authenticator/api/authenticate/**
            - Method=POST,GET,PUT,DELETE,HEAD,OPTIONS,PATCH
#            - Header=**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'
              maxAge: 30
          filters:
#            - AddRequestHeader=Hello,World
#            - StripPrefix=1  
# ws-administrator
#  privilegy
        - id: ws-administrator
          uri: lb://ws-administrator
          predicates: 
            - Path=/ws-administrator/api/privilegy
            - Method=POST,GET,PUT,DELETE,HEAD,OPTIONS,PATCH
#            - Header=**            
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'
              maxAge: 30
          filters:
#            - AddRequestHeader=Hello,World
 #           - StripPrefix=1           
# ws-sysAdmin
        - id: ws-sysAdmin
          uri: lb://ws-sysAdmin
          predicates: 
            - Path=/ws-sysAdmin/api/privilegy
            - Method=POST,GET,PUT,DELETE,HEAD,OPTIONS,PATCH
#            - Header=**          
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'
              maxAge: 30
          filters:
#            - AddRequestHeader=Hello,World
  #          - StripPrefix=1           
##ws-email
        - id: ws-email
          uri: lb://ws-email
          predicates: 
            - Path=/ws-email/**
            - Method=POST,GET,PUT,DELETE,HEAD,OPTIONS,PATCH
#            - Header=**            
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'
              maxAge: 30
          filters:
#            - AddRequestHeader=Hello,World
    #        - StripPrefix=1
##ws-email
        - id: ws-config-server
          uri: lb://ws-config-server
          predicates: 
            - Path=/ws-config-server/**
            - Method=POST,GET,PUT,DELETE,HEAD,OPTIONS,PATCH
#            - Header=**            
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'
              maxAge: 30
          filters:
#            - AddRequestHeader=Hello,World
    #        - StripPrefix=1
        
