spring:
  cloud:
   gateway: 
      routes: 
        - id: my_route
          uri: http://httpbin.org:80
          predicates: 
            - Path=/get/**
          filters:
            - AddRequestHeader=Hello,World
           # - StripPrefix=1  
# ws-authenticator
# user endpoint
        - id: ws-authenticator
          uri: lb://ws-authenticator
          predicates: 
            - Path=/ws-authenticator/**
            - Method=POST,GET,PUT,DELETE
#            - Header=**
          filters:
#            - AddRequestHeader=Hello,World
#            - StripPrefix=1  
# ws-administrator
#  privilegy
        - id: ws-administrator
          uri: lb://ws-administrator
          predicates: 
            - Path=/ws-administrator/**
            - Method=POST,GET,PUT,DELETE
#            - Header=**            
          filters:
#            - AddRequestHeader=Hello,World
 #           - StripPrefix=1           
# ws-sysAdmin
        - id: ws-sysAdmin
          uri: lb://ws-sysAdmin
          predicates: 
            - Path=/ws-sysAdmin/**
            - Method=POST,GET,PUT,DELETE
#            - Header=**          
          filters:
#            - AddRequestHeader=Hello,World
  #          - StripPrefix=1           
##ws-email
        - id: ws-email
          uri: lb://ws-email
          predicates: 
            - Path=/ws-email/**
            - Method=POST,GET,PUT,DELETE
#            - Header=**            
          filters:
#            - AddRequestHeader=Hello,World
    #        - StripPrefix=1
##ws-config server
        - id: ws-config-server
          uri: lb://ws-config-server
          predicates: 
            - Path=/ws-config-server/**
            - Method=POST,GET,PUT,DELETE
#            - Header=**            
          filters:
#            - AddRequestHeader=Hello,World
    #        - StripPrefix=1
##ws-eureka-server
        - id: ws-eureka-server
          uri: lb://ws-eureka-server
          predicates: 
            - Path=/ws-eureka-server/**
            - Method=POST,GET,PUT,DELETE
#            - Header=**            
          filters:
#            - AddRequestHeader=Hello,World
    #        - StripPrefix=1
##ws-admin server
        - id: ws-admin-server
          uri: lb://ws-admin-server
          predicates: 
            - Path=/ws-admin-server/**
            - Method=POST,GET,PUT,DELETE
#            - Header=**            
          filters:
#            - AddRequestHeader=Hello,World
    #        - StripPrefix=1
