spring:
  cloud:
   gateway: 
      routes: 
        - id: my_route
          uri: http://httpbin.org:80
          predicates: 
            - Path=/get/**
          filters:
            - AddRequestHeader=Hello,World
# user endpoint
        - id: ws-authenticator
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/api/authenticate/**
            - Method=POST
          filters:
#            - AddRequestHeader=Hello,World
#            - StripPrefix=1           
        - id: /ws-authenticator/api/user/create
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user
            - Method=POST
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/user/get
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /api/user/auth/
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/api/user/auth/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
#            - StripPrefix=1
        - id: /ws-authenticator/api/user/all
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user/all
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/user/update
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user
            - Method=PUT
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/user/delete
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user
            - Method=DELETE
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
## authioritie endpoint 
        - id: /ws-authenticator/api/authority/create
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authority
            - Method=POST
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/authority/get
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authority/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/authority/all
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authority/all
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/authority/update
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authority
            - Method=PUT
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/authority/delete
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authority
            - Method=DELETE
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/swagger-ui/index.html
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/swagger-ui/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/pi-docs/
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api-docs/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
#  privilegy
        - id: /ws-administrator/api/privilegy/create
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy
            - Method=POST
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1           
        - id: /ws-administrator/api/privilegy/get
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1     
        - id: /ws-administrator/api/privilegy/all
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy/all
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1     
        - id: /ws-administrator/api/privilegy/allByRole
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy/allByRole/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1     
        - id: /ws-administrator/api/privilegy/update
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy
            - Method=PUT
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-administrator/api/privilegy/delete
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy
            - Method=DELETE
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
#  company
        - id: /ws-administrator/api/company/create
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/company
            - Method=POST
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1           
        - id: /ws-administrator/api/company/get
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/company/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1     
        - id: /ws-administrator/api/company/all
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/company/all
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1        
        - id: /ws-administrator/api/company/update
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/company
            - Method=PUT
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-administrator/api/company/delete
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/company
            - Method=DELETE
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1

