spring:
  cloud:
   gateway: 
      routes: 
#  privilegy
        - id: /ws-administrator/api/privilegy/create
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy
            - Method=POST
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1           
       - id: /ws-administrator/api/privilegy/get
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1     
       - id: /ws-administrator/api/privilegy/all
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy/all
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1     
       - id: /ws-administrator/api/privilegy/allByRole
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy/allByRole/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1     
        - id: /ws-administrator/api/privilegy/update
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy
            - Method=PUT
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-administrator/api/privilegy/delete
          uri: lb://WS-ADMINISTRATOR
          predicates: 
            - Path=/ws-administrator/api/privilegy
            - Method=DELETE
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
