MYSQL_HOST: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
spring:
  config:
    import: eureka-conf.yml
  datasource:
  # password: o649fj9325yuhwx9
    password: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
 #  username: y3wh6gobj769qsq7
    username: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
 #  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eqzllf9uo0wemtvb
    url: jdbc:mysql://ENC(Uxqp1U8XrvvVzErY2P4ytQ==):3306/administrator
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: http://ENC(Uxqp1U8XrvvVzErY2P4ytQ==):8096
            username: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
            password: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
logging:
  config: classpath:logback-dev.xml
