management:
#  server:
#    base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    pause:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
#      base-path: /actuator
      exposure:
        include: '*'
spring:
# boot:
#    admin:
#      discovery:
#        ignored-services: ws-api-gateway
eureka:    
  instance:
#    statusPageUrlPath: ${server.servlet.context-path}${management.endpoints.web.base-path}/info
#   healthCheckUrlPath: ${server.servlet.context-path}${management.endpoints.web.base-path}/health
    instanceId: ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}
