MYSQL_HOST: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
spring:
  config:
    import: eureka-conf.yml,rabbitLoggerFilter-dev.yml
 # application:
  #  name: ws-authenticator
  datasource:
    #password: o649fj9325yuhwx9
    password: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: y3wh6gobj769qsq7
    username: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
    url: jdbc:mysql://${MYSQL_HOST:ENC(Uxqp1U8XrvvVzErY2P4ytQ==)}:3306/authentication
    #url: jdbc:mysql://authentication.cdwuqk40emj5.us-west-1.rds.amazonaws.com:3306/authentication
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
          wsEmail:
            url: http://ENC(Uxqp1U8XrvvVzErY2P4ytQ==):8096/ws-email
          wsAuthenticator:
            url: http://ENC(Uxqp1U8XrvvVzErY2P4ytQ==):8096/ws-authenticator
            username: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
            password: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
