MYSQL_HOST: y3wh6gobj769qsq7:o649fj9325yuhwx9@dcrhg4kh56j13bnu.cbetxkdyhwsb.us-east-1.rds.amazonaws.com

secret:
  key: +KbPeShVmYq3t6v9y$B&E)H@McQfTjWnZr4u7x!z%C*F-JaNdRgUkXp2s5v8y/B?
  expiration_time_minutes: 60
  
server:
  servlet:
    context-path: /ws-authenticator
  port: '8083'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
spring:
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:${server.port}
        url: http://localhost:8094/ws-admin-server
        username: wsAdminServer
        password: 'ws4dm1nS3rv3r*'
 # application:
  #  name: ws-authenticator
  datasource:
  # password: o649fj9325yuhwx9
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
 #  username: y3wh6gobj769qsq7
    username: root
 #  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eqzllf9uo0wemtvb
    url: jdbc:mysql://localhost:3306/authentication
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  config: classpath:logback-dev.xml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/ws-eureka-server
    

  
