spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:8094
#        username: wsAdminServer
#        password: 'ws4dm1nS3rv3r*'
  cloud: 
    gateway: 
      routes: 
        - id: my_route
          uri: http://httpbin.org:80
          predicates: 
            - Path=/get/**
          filters:
            - AddRequestHeader=Hello,World
#            - StripPrefix=1
# user endpoint

        - id: ws-authenticator
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authenticate/**
            - Method=POST
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1           
        - id: /ws-authenticator/api/user/create
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user
            - Method=POST
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/user/get
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/user/auth/
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user/auth/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/user/all
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user/all
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/user/update
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user
            - Method=PUT
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
       - id: /ws-authenticator/api/user/delete
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/user
            - Method=DELETE
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
## authioritie endpoint 
        - id: /ws-authenticator/api/authority/create
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authority
            - Method=POST
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/authority/get
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authority/**
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/authority/all
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authority/all
            - Method=GET
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: /ws-authenticator/api/authority/update
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authority
            - Method=PUT
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
       - id: /ws-authenticator/api/authority/delete
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/authority/user
            - Method=DELETE
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
              
logging:
  config: classpath:logback-dev.xml
eureka:
#  context-path: /ws-eureka-server
  single-instance:
    host: localhost
    port: 8761
  client:
    service-url: 
      defaultZone: http://${eureka.single-instance.host}:${eureka.single-instance.port}/eureka
