MYSQL_HOST: y3wh6gobj769qsq7:o649fj9325yuhwx9@dcrhg4kh56j13bnu.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
spring:
# boot:
#   admin:
#     client:
#      instance:
#          service-base-url: http://localhost:${server.port}
#       url: http://localhost:8094
#       username: wsAdminServer
#       password: 'ws4dm1nS3rv3r*'
#    admin:
#      discovery:
#        ignored-services: ws-api-gateway
 datasource:
  # password: o649fj9325yuhwx9
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
 #  username: y3wh6gobj769qsq7
    username: root
 #  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eqzllf9uo0wemtvb
    url: jdbc:mysql://localhost:3306/authentication
    hikari:
      maximum-pool-size: 5
 jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  api-docs:
#    path: /api-docs  
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
logging:
 config: classpath:logback-dev.xml
