spring:
#  config:
#    import: endpoints-authenticator.yml
#  boot:
#    admin:
#      client:
#        url: http://localhost:8094
#        username: wsAdminServer
#        password: 'ws4dm1nS3rv3r*'
#eureka:
#  context-path: /ws-eureka-server
#  single-instance:
#    host: localhost
#    port: 8761
#  client:
#    service-url: 
#      defaultZone: http://${eureka.single-instance.host}:${eureka.single-instance.port}/eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.100.15:8761/eureka}
  instance:
    preferIpAddress: true
