management:
  endpoint:
    health:
      enabled: true
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true   
  shutdown:
    enabled: true
  pause:
    enabled: true
  restart:
    enabled: true
  refresh:
    enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
server:
  servlet:
    context-path: /ws-api-gateway
  port: 8096
spring:
  main:
    web-application-type: REACTIVE
#  webflux:
#    base-path: /ws-api-gateway
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:${server.port}
        url: http://localhost:8094/ws-admin-server
        username: wsAdminServer
        password: 'ws4dm1nS3rv3r*'
  cloud: 
    gateway: 
      routes: 
        - id: my_route
          uri: http://httpbin.org:80
          predicates: 
            - Path=/get/**
          filters:
            - AddRequestHeader=Hello,World
            - StripPrefix=1
        - id: ws-authenticator
          uri: lb://WS-AUTHENTICATOR
          predicates: 
            - Path=/ws-authenticator/api/authenticate/**
            - Method=POST
          filters:
#            - AddRequestHeader=Hello,World
            - StripPrefix=1
              
logging:
  config: classpath:logback-dev.xml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
eureka:
  context-path: /ws-eureka-server
  single-instance:
    host: localhost
    port: 8761
  client:
    service-url: 
      defaultZone: http://${eureka.single-instance.host}:${eureka.single-instance.port}${eureka.context-path}/eureka
