MYSQL_HOST: 50.18.24.43
spring:
  config:
    import: eureka-conf.yml,rabbitLoggerFilter-dev.yml
 # application:
  #  name: ws-authenticator
  datasource:
    #password: o649fj9325yuhwx9
    password: ws4uth3nt1c4t0rDB*
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: y3wh6gobj769qsq7
    username: wsAuthenticatorDB
    url: jdbc:mysql://${MYSQL_HOST:50.18.24.43}:3306/authentication
    #url: jdbc:mysql://authentication.cdwuqk40emj5.us-west-1.rds.amazonaws.com:3306/authentication
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
          wsEmail:
            url: http://localhost:8096/ws-email
          wsAuthenticator:
            url: http://localhost:8096/ws-authenticator
            username: wsAuthenticator
            password: ws4uth3nt1c4t0r*
