server:
#  servlet:
#    context-path: /ws-config-server
  port: '8095'
management:
#  server:
#    base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    pause:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true   
  endpoints:
    web:
#      base-path: ${server.servlet.context-path}/actuator
      exposure:
        include: '*'
