spring:
  config:
    import: eureka-conf.yml
  datasource:
  # password: o649fj9325yuhwx9
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
 #  username: y3wh6gobj769qsq7
    username: root
 #  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eqzllf9uo0wemtvb
    url: jdbc:mysql://localhost:3306/authentication
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
