management:
#  server:
#    base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true   
  shutdown:
    enabled: true
  pause:
    enabled: true
  restart:
    enabled: true
  refresh:
    enabled: true
  endpoints:
    web:
#      base-path: ${server.servlet.context-path}/actuator
      exposure:
        include: '*'
server:
  servlet:
    context-path: /ws-eureka-server
  port: 8761
spring:
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:8761
        url: http://localhost:8094/ws-admin-server
        username: wsAdminServer
        password: 'ws4dm1nS3rv3r*'
eureka:
 instance:
   hostname: 'localhost'
   statusPageUrlPath: ${server.servlet.context-path}/info
   healthCheckUrlPath: ${server.servlet.context-path}/health
 client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/
# For single Eureka instance
 

 
logging:
  config: classpath:logback-dev.xml           
