aws:
  bucketName: boyertech
  fileName: email-templates/confirmation_signing_up.html  
MYSQL_HOST: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
spring:
  mail:
    host: ENC(email-smtp.us-west-1.amazonaws.com)
    sender: ENC(notificaciones@boyertech.com.mx)
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
          port: '587'
        transport:
          protocol: smtp  
  config:
    import: eureka-conf.yml,rabbitLoggerFilter-dev.yml
  cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: http://ENC(Uxqp1U8XrvvVzErY2P4ytQ==):8096/ws-authenticator
            username: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
            password: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
