spring:
#  boot:
#    admin:
#     client:
#        url: http://localhost:8094
#        username: wsAdminServer
#        password: 'ws4dm1nS3rv3r*'
#eureka:
# instance:
#   hostname: 'localhost'
#   statusPageUrlPath: ${management.endpoints.web.base-path}/info
#   healthCheckUrlPath: ${management.endpoints.web.base-path}/health
#   instanceId: ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}
# client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#            defaultZone: http://${eureka.instance.hostname}:${server.port}/
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.100.15:8761/eureka}
  instance:
    preferIpAddress: true
  server:
    enableSelfPreservation: false

# For single Eureka instance
