server:
  servlet:
    context-path: /ws-eureka-server
  port: ${PORT:8761}
logging:
 config: classpath:logback-dev.xml
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    pause:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true   
  endpoints:
    web:
      exposure:
        include: '*'
rabbitmq:
  logger:
    filter:
      enabled: false
      exchange-fanout: ws.logger.fanout
      exchange-direct: ws.logger.direct
      exchange-topic: ws.logger.topic
      queue: ws.logger.requestLogger 
      virtual-host: com.boyertech.logger  # Si tienes un virtual host configurado
      password: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
      port: '5671'
      host: ${RABBIT_URI:ENC(Uxqp1U8XrvvVzErY2P4ytQ==)}
      username: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
      ssl:
     #   enabled: true
        algorithm: TLSv1.2
        key-store: /mykeystore.jks  # Si usas un keystore
#        key-store: classpath:mykeystore.jks  # Si usas un keystore
        key-store-password: ENC(wsL0gg3r*)
        trust-store: /mytruststore.jks  # Si usas un truststore
#        trust-store: classpath:mytruststore.jks  # Si usas un truststore
        trust-store-password: ENC(wsL0gg3r*)  
spring:
  config:
    import: eureka-conf-dev.yml
  datasource:
    #password: o649fj9325yuhwx9
    password: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: y3wh6gobj769qsq7
    username: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
    url: jdbc:mysql://${MYSQL_HOST:ENC(Uxqp1U8XrvvVzErY2P4ytQ==)}:3306/authentication
    #url: jdbc:mysql://authentication.cdwuqk40emj5.us-west-1.rds.amazonaws.com:3306/authentication
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
