aws:
  bucketName: boyertech
  fileName: email-templates/confirmation_signing_up.html  
MYSQL_HOST: y3wh6gobj769qsq7:o649fj9325yuhwx9@dcrhg4kh56j13bnu.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
spring:
  mail:
    host: email-smtp.us-west-1.amazonaws.com
    sender: notificaciones@boyertech.com.mx
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
          port: '587'
        transport:
          protocol: smtp  
  config:
    import: eureka-conf.yml,rabbitLoggerFilter-dev.yml
  cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: http://localhost:8096/ws-authenticator
            username: wsEmail
            password: ws3m41l*
