management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    pause:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
    health:
      enabled: true
      show-details: always
server:
  servlet:
    context-path: /ws-eureka-server
  port: '8761'
spring:
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:8761
        url: http://localhost:8094/ws-admin-server
        username: wsAdminServer
        password: 'ws4dm1nS3rv3r*'
eureka:
 instance:
   hostname: 'localhost'
 client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/
# For single Eureka instance
 

 
logging:
  config: classpath:logback-dev.xml           
