spring:
#eureka:
# instance:
#   hostname: 'localhost'
#   statusPageUrlPath: ${management.endpoints.web.base-path}/info
#   healthCheckUrlPath: ${management.endpoints.web.base-path}/health
#   instanceId: ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}
# client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#            defaultZone: http://${eureka.instance.hostname}:${server.port}/
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.100.15:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  server:
    enableSelfPreservation: true

# For single Eureka instance
