MYSQL_HOST: y3wh6gobj769qsq7:o649fj9325yuhwx9@dcrhg4kh56j13bnu.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
spring:
  mail:
  config:
    import: eureka-conf.yml
  datasource:
    password: o649fj9325yuhwx9
    #password: wsL0gg3rDB*
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: y3wh6gobj769qsq7
    #username: wsLoggerDB
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eqzllf9uo0wemtvb
    #url: jdbc:mysql://logger.cdwuqk40emj5.us-west-1.rds.amazonaws.com:3306/logger
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: http://localhost:8096/ws-authenticator
            username: wsLogger
            password: wsL0gg3r*
