MYSQL_HOST: y3wh6gobj769qsq7:o649fj9325yuhwx9@dcrhg4kh56j13bnu.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
spring:
  config:
    import: eureka-conf.yml,rabbitLoggerFilter-dev.yml
  datasource:
  # password: o649fj9325yuhwx9
    password: wsSys4dm1nDB*
    driver-class-name: com.mysql.cj.jdbc.Driver
 #  username: y3wh6gobj769qsq7
    username: wsSysAdminDB
 #  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eqzllf9uo0wemtvb
    url: jdbc:mysql://sysadmin.cdwuqk40emj5.us-west-1.rds.amazonaws.com/sys_admin
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: http://localhost:8096/ws-authenticator
            username: wsSysAdmin
            password: wsSys4dm1n*
logging:
  config: classpath:logback-dev.xml
