MYSQL_HOST: 50.18.24.43
spring:
  config:
    import: eureka-conf.yml,rabbitLoggerFilter-dev.yml
  cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: http://localhost:8096/ws-authenticator
            username: wsEmail
            password: ws3m41l*
