MYSQL_HOST: y3wh6gobj769qsq7:o649fj9325yuhwx9@dcrhg4kh56j13bnu.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
spring:
  datasource:
  # password: o649fj9325yuhwx9
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
 #  username: y3wh6gobj769qsq7
    username: root
 #  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eqzllf9uo0wemtvb
    url: jdbc:mysql://localhost:3306/sys_admin
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: http://192.168.100.15:8096
            username: wsAdministrator
            password: ws4dm1n1str4t0r*
logging:
  config: classpath:logback-dev.xml
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.100.15:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
