MYSQL_HOST: 50.18.24.43
spring:
  config:
    import: eureka-conf.yml,rabbitLoggerFilter-dev.yml
  datasource:
    #password: o649fj9325yuhwx9
    password: wsSys4dm1nDB*
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: y3wh6gobj769qsq7
    username: wsSysAdminDB
    url: jdbc:mysql://${MYSQL_HOST:50.18.24.43}:3306/sys_admin
    #url: jdbc:mysql://sysadmin.cdwuqk40emj5.us-west-1.rds.amazonaws.com:3306/sys_admin
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: http://localhost:8096/ws-authenticator
            username: wsSysAdmin
            password: wsSys4dm1n*
logging:
  config: classpath:logback-dev.xml
