MYSQL_HOST: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
spring:
  config:
    import: eureka-conf.yml,rabbitLoggerFilter-dev.yml
  cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: http://ENC(Uxqp1U8XrvvVzErY2P4ytQ==):8096/ws-authenticator
            username: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
            password: ENC(Uxqp1U8XrvvVzErY2P4ytQ==)
